#!/bin/sh
set -e
if ! [ -e /tmp/opendatanow-trigger-fifo ] ; then
    mkfifo -m0660 /tmp/opendatanow-trigger-fifo
    chgrp www-data /tmp/opendatanow-trigger-fifo
fi

while true ; do
    ./cycle
    cat /tmp/opendatanow-trigger-fifo		# Wait for another update FIXME - race condition
    sleep 3
done
